name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku
        uses: heroku/actions@v0.0.1  

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git@heroku.com:<restaurant-management-system>.git
          git push heroku main
